[theme]
base="dark"
primaryColor="#DAA520"          # Goldenrod (close to gold)
backgroundColor="#212329ff"       # Parchment
secondaryBackgroundColor="#4e4334ff"  # Tan/wood
textColor="#DAA520"            # Gold text
font="serif"                    # Old-style serif font
