[theme]
base="dark"
primaryColor="#DAA520"          # Goldenrod (close to gold)
backgroundColor="#313034ff"       # Parchment
secondaryBackgroundColor="#d2b48c"  # Tan/wood
textColor="#1a2034ff"             # Gold text
font="serif"                    # Old-style serif font
